// Code generated by AI and checked/modified for correctness

import type { ScaleLinear } from "d3";
import * as d3 from "d3";
import { For } from "solid-js";

interface AxisProps {
  scale: ScaleLinear<number, number>;
  transform?: string;
  tickCount?: number;
}

export const AxisBottom = (props: AxisProps) => {
  const ticks = () => {
    const domain = props.scale.domain();
    const tickCount = props.tickCount || 5;
    const step = (domain[1] - domain[0]) / (tickCount - 1);

    return [...Array(tickCount).keys()].map((i) => {
      const value = domain[0] + i * step;
      return {
        value,
        position: props.scale(value),
      };
    });
  };

  return (
    <g transform={props.transform}>
      <line
        x1={props.scale.range()[0]}
        x2={props.scale.range()[1]}
        y1="0"
        y2="0"
        stroke="currentColor"
      />
      <For each={ticks()}>
        {(tick) => (
          <g transform={`translate(${tick.position}, 0)`}>
            <line y2="6" stroke="currentColor" />
            <text y="9" dy="0.71em" text-anchor="middle">
              {d3.format(".3g")(tick.value)}
            </text>
          </g>
        )}
      </For>
    </g>
  );
};

export const AxisLeft = (props: AxisProps) => {
  const ticks = () => {
    const domain = props.scale.domain();
    const tickCount = props.tickCount || 5;
    const step = (domain[1] - domain[0]) / (tickCount - 1);

    return [...Array(tickCount).keys()].map((i) => {
      const value = domain[0] + i * step;
      return {
        value,
        position: props.scale(value),
      };
    });
  };

  return (
    <g transform={props.transform}>
      <line
        x1={0}
        x2={0}
        y1={props.scale.range()[0]}
        y2={props.scale.range()[1]}
        stroke="currentColor"
      />
      <For each={ticks()}>
        {(tick) => (
          <g transform={`translate(0, ${tick.position})`}>
            <line x2="-6" stroke="currentColor" />
            <text x="-9" dy="0.32em" text-anchor="end">
              {tick.value.toFixed()}
            </text>
          </g>
        )}
      </For>
    </g>
  );
};
