/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ABLHeight = number;
/**
 * The potential temperature of the mixed layer at the initial time.
 */
export type MixedLayerPotentialTemperatureK = number;
export type TemperatureJumpAtHK = number;
export type MixedLayerSpecificHumidityKgKg1 = number;
export type SpecificHumidityJumpAtHKgKg1 = number;
export type TimeStepS = number;
export type TotalRunTimeS = number;
export type SurfaceKinematicHeatFluxKMS1 = number;
export type AdvectionOfHeatKS1 = number;
export type FreeAtmospherePotentialTemperatureLapseRateKM1 = number;
export type SurfaceKinematicMoistureFluxKgKg1MS1 = number;
export type AdvectionOfMoistureKgKg1S1 = number;
export type FreeAtmosphereSpecificHumidityLapseRateKgKg1M1 = number;
export type HorizontalLargeScaleDivergenceOfWindS1 = number;
export type EntrainmentRatioForVirtualHeat = number;

export interface Config {
  initialState: InitialState;
  timeControl: TimeControl;
  mixedLayer: MixedLayer;
}
export interface InitialState {
  h_0: ABLHeight;
  theta_0: MixedLayerPotentialTemperatureK;
  dtheta_0: TemperatureJumpAtHK;
  q_0: MixedLayerSpecificHumidityKgKg1;
  dq_0: SpecificHumidityJumpAtHKgKg1;
}
export interface TimeControl {
  dt: TimeStepS;
  runtime: TotalRunTimeS;
}
export interface MixedLayer {
  wtheta: SurfaceKinematicHeatFluxKMS1;
  advtheta: AdvectionOfHeatKS1;
  gammatheta: FreeAtmospherePotentialTemperatureLapseRateKM1;
  wq: SurfaceKinematicMoistureFluxKgKg1MS1;
  advq: AdvectionOfMoistureKgKg1S1;
  gammaq: FreeAtmosphereSpecificHumidityLapseRateKgKg1M1;
  divU: HorizontalLargeScaleDivergenceOfWindS1;
  beta: EntrainmentRatioForVirtualHeat;
}
