/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Config {
  /**
   * Initial State
   */
  initialState: {
    /**
     * Initial ABL height [m]
     */
    h_0: number;
    /**
     * Initial mixed-layer potential temperature [K]
     */
    theta_0: number;
    /**
     * Initial temperature jump at h [K]
     */
    dtheta_0: number;
    /**
     * Initial mixed-layer specific humidity [kg kg-1]
     */
    q_0: number;
    /**
     * Initial specific humidity jump at h [kg kg-1]
     */
    dq_0: number;
  };
  /**
   * Time control
   */
  timeControl: {
    /**
     * Time step [s]
     */
    dt: number;
    /**
     * Total run time [s]
     */
    runtime: number;
  };
  /**
   * Mixed layer
   */
  mixedLayer: {
    /**
     * Surface kinematic heat flux [K m s-1]
     */
    wtheta: number;
    /**
     * Advection of heat [K s-1]
     */
    advtheta: number;
    /**
     * Free atmosphere potential temperature lapse rate [K m-1]
     */
    gammatheta: number;
    /**
     * Surface kinematic moisture flux [kg kg-1 m s-1]
     */
    wq: number;
    /**
     * Advection of moisture [kg kg-1 s-1]
     */
    advq: number;
    /**
     * Free atmosphere specific humidity lapse rate [kg kg-1 m-1]
     */
    gammaq: number;
    /**
     * Horizontal large-scale divergence of wind [s-1]
     */
    divU: number;
    /**
     * Entrainment ratio for virtual heat [-]
     */
    beta: number;
  };
}
