/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ABLHeight = number;
/**
 * The potential temperature of the mixed layer at the initial time.
 */
export type MixedLayerPotentialTemperature = number;
export type TemperatureJumpAtH = number;
export type MixedLayerSpecificHumidity = number;
export type SpecificHumidityJumpAtH = number;
export type TimeStep = number;
export type TotalRunTime = number;
export type SurfaceKinematicHeatFlux = number;
export type AdvectionOfHeat = number;
export type FreeAtmospherePotentialTemperatureLapseRate = number;
export type SurfaceKinematicMoistureFlux = number;
export type AdvectionOfMoisture = number;
export type FreeAtmosphereSpecificHumidityLapseRate = number;
export type HorizontalLargeScaleDivergenceOfWind = number;
export type EntrainmentRatioForVirtualHeat = number;

export interface Config {
  initialState: InitialState;
  timeControl: TimeControl;
  mixedLayer: MixedLayer;
}
export interface InitialState {
  h_0: ABLHeight;
  theta_0: MixedLayerPotentialTemperature;
  dtheta_0: TemperatureJumpAtH;
  q_0: MixedLayerSpecificHumidity;
  dq_0: SpecificHumidityJumpAtH;
}
export interface TimeControl {
  dt: TimeStep;
  runtime: TotalRunTime;
}
export interface MixedLayer {
  wtheta: SurfaceKinematicHeatFlux;
  advtheta: AdvectionOfHeat;
  gammatheta: FreeAtmospherePotentialTemperatureLapseRate;
  wq: SurfaceKinematicMoistureFlux;
  advq: AdvectionOfMoisture;
  gammaq: FreeAtmosphereSpecificHumidityLapseRate;
  divU: HorizontalLargeScaleDivergenceOfWind;
  beta: EntrainmentRatioForVirtualHeat;
}
